---
title: "Assigenment 4"
output: html_document
---

##Question1
#a).
```{r}
seq(1:20)
# Create a vector from 1 to 20
```
#b).
```{r}
n<-20
c<-(n:1)
c
# Create a vector c from 20 to 1
```

#c).
```{r}
c(1:20,19:1)
# Create a vector c from 1 to 20 and then to 1
```

#d).
```{r}
tmp<-c(4,6,3)
tmp
# Create a vector tmp as (4,6,3)
```

#e).
```{r}
rep(tmp,10)
# Create a vector repeat tmp for 10 times
```

#f). 
```{r}
rep(tmp,l=31)
# Create a vector there are 11 occurences of 4, 
# 10 occurences of 6 and 10 occurences of 3.
```

#g).
```{r}
rep(tmp,times=c(10,20,30))
# Create a vector there are 10 occurences of 4,
# 20 occurences of 6 and 30 occurences of 3.
```

##Question 2
```{r}
x<-seq(3,6,by=0.1)
exp(x)*cos(x)
# Create a vector of the values of e^x cos(x)
# Where x = 3,3.1,3.2,...,5.9,6
```

##Question 3
#a).
```{r}
(0.1^seq(3,36,by=3))*(0.2^seq(1,34,by=3))
# Create a vector of (0.1^3x0.2^1,0.1^6x0.2^4,...,0.1^36x0.2^34)
```

#b).
```{r}
(2^seq(1,25,by=1))/(1:25)
# Create a vector of (2,2^2/2,2^3/3,...,2^25/25)
```

##Question 4
#a).
```{r}
i=seq(1,100,by=1)
sum(i^3+4*i^2)
# Calculate the sum of (i^3+4i^2), where i belongs to (1,100)
```

#b).
```{r}
i=seq(1,25,by=1)
sum(2^i/i + 3^i/i^2)
# Calculate the sum of (2^i/i+3^i/i^2), where i belongs to (1,25)
```

##Question 5
#a).
```{r}
paste('label',1:30)
# Paste the label from 1 to 30 and there is a single space
```

#b).
```{r}
paste('fn',1:30,sep="")
# Paste the fn from 1 to 30 and there is no space between fn
```

##Question 6
set.seed(50)

xVec<-sample(0:999,250,replace=T)

yVec<-sample(0:999,250,replace=T)

#a).
```{r}
yVec[c(2:250)]-xVec[c(1:249)]
# Create the vector of (y_2-x_1,...,y_n-y_(n-1))
```

#b).
```{r}
sin(yVec[c(1:249)])/cos(xVec[c(2:250)])
# Create the vector of (sin(y_1)/cos(x_2),sin(y_2)/cos(x_3),...,sin(y_(n-1))/cos(x_n))
```

#c).
```{r}
xVec[c(1:248)]+2*xVec[c(2:249)]-xVec[c(3:250)]
# Create the vector of (x_1+2x_2-x_3,...,x_(n-2)+2x_(n-1)-x_n)
```

#d).
```{r}
sum(exp(-xVec[c(2:250)])/(xVec[c(1:249)]+10))
# Calculate the sum of (e^{-x}_{i+1}/x_i+10)
```

##Question 7 
```{r}
set.seed(50)
xVec<-sample(0:999,250,replace=T)
yVec<-sample(0:999,250,replace=T)
```
#a).
```{r}
y600<-yVec[yVec>600]
y600
# define a variable y600 to Pick out the values in yVec which are > 600
```

#b).
```{r}
which(yVec>600)
# To find the index positions in yVec of the values which are > 600
```

#c).
```{r}
x600<-xVec[yVec>600]
# To find the values in xVec which are > 600
```
#d).
```{r}
sqrt(abs(xVec-mean(xVec)))
# Create the vector to find the absolute value of (x_i - bar{x})^{1/2}
```

#e).
```{r}
sum(yVec>max(yVec)-200)
# To find how many values in yVec are within 200 of the maximum value of the terms in yVec
```

#f).
```{r}
sum(xVec%%2==0)
# To find how many valuew in xVec are modulo 2.
```

#g).
```{r}
xVec[order(yVec)]
# Sort the numbers in the vector xVec in the order of increasing values in yVec
```
#h).
```{r}
yVec[c(T,F,F)]
# Pick out the elements in yVec at index positions 1,4,7,10,13,...
```

##Question 8
```{r}
1+sum(cumprod(seq(2,38,by=2)/seq(3,39,by=2)))
# calculate the cumprod of the function 
```













